<a href="https://colab.research.google.com/github/vittoriadelsignore/Python/blob/main/Concatenar_y_Separar_Arrays_con_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
array = np.full(5, 5)
array[0] = 1


print(array)


[1 5 5 5 5]


In [12]:
array = np.random.randint(5, size=(2,3))    #aleatorios menores a 5, de tamaño 2x3

print(array)

[[0 0 1]
 [4 0 4]]


In [13]:
array1 = np.ones(5)             #array con solo valores iguales a 1
array2 = np.zeros(3)            #array con solo valores iguales a 0

def recibearrays(array1, array2):            #creacion de funcion concatenar y split
  array=[]
  arrays_concatenados=np.concatenate([array1,array2])
  arrays_partidos=np.split(arrays_concatenados,[4])
  return array


In [15]:
array1 = [1, 5, 300, 2, 0, 22]
array2 = [2, 5, 3]

In [16]:
def mitad(a1,a2):          #funcion para crear mitades
  a3=np.concatenate([a1,a2])        #concatena los arrays 1 y 2
  mitad1,mitad2=np.split(a3,[a3.shape[0]//2])      #los separa por la mitad
  return mitad1,mitad2,a3                         #muestra la primera mitad, la segunda mitad y el concatenado del array 1 y 2

mitad(np.ones(5),np.zeros(3))     #aplicar la función

(array([1., 1., 1., 1.]),
 array([1., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 0., 0., 0.]))

In [17]:
a1 = [1, 5, 300, 2, 0, 22]      #definimos un nuevo array 1
a2 = [2, 5, 3]                  #definimos un nuevo array 2

def mitad(a1,a2):
  a3=np.concatenate([a1,a2])
  mitad1,mitad2=np.split(a3,[a3.shape[0]//2])
  return mitad1,mitad2,a3

mitad(a1,a2)       # aplicamos la función definida

(array([  1,   5, 300,   2]),
 array([ 0, 22,  2,  5,  3]),
 array([  1,   5, 300,   2,   0,  22,   2,   5,   3]))

In [18]:
a3=np.concatenate([a1,a2])       # concatenar ambos arrays
a3

array([  1,   5, 300,   2,   0,  22,   2,   5,   3])

In [21]:
 mitad1,mitad2=np.split(a3,[a3.shape[0]//2])     # separar en mitades
 mitad1,mitad2


(array([  1,   5, 300,   2]), array([ 0, 22,  2,  5,  3]))

In [23]:
mitad1    # ver solo la primera mitad

array([  1,   5, 300,   2])

In [24]:
mitad2    # ver solo la segunda mitad

array([ 0, 22,  2,  5,  3])

In [26]:
mitad1.mean()      # calcular el promedio de la primera mitad

77.0

In [27]:
np.median(mitad1)     # calcular la mediana de la primera mitad

3.5

In [28]:
np.std(mitad1)    # calcular la desviación estandard de la primera mitad

128.75752405199472